---
- hosts: all
  remote_user: root
  tasks:
   - name: install httpd package
     yum:
      name: httpd
      state: latest
   - name: start apache
     service:
       name: httpd
       state: started

 
