---
- hosts: all
  tasks:
   - name: install httpd package
     yum:
      name: httpd
      state: latest
   - name: start apache
     service:
       name: httpd
       state: started

  delegate_to: 127.0.0.1   
